### ISSUE TITLE
TypeError: '>=' not supported between instances of 'str' and 'int'

### ISSUE THREAD

**Issue by Mespith** [sassoftware/python-dlpy#261]
I'm trying to create an object detection dataset using the notebook in the examples: [PrepareObjectDetectionTable.ipynb](https://github.com/sassoftware/python-dlpy/blob/master/examples/object_detection/PrepareObjectDetectionTable.ipynb) When I run the code
```
object_detection_targets = create_object_detection_table(s, 
                                                         data_path = '/home/snljdk/data/IJBurg_Afval',
                                                         coord_type = 'yolo', 
                                                         output = 'detTbl')
```
I get the following error
```
NOTE: Images are processed.
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-5b5617c51872> in <module>
      2                                                          data_path = '/home/snljdk/data/IJBurg_Afval',
      3                                                          coord_type = 'yolo',
----> 4                                                          output = 'detTbl')

/opt/anaconda3/lib/python3.7/site-packages/dlpy/utils.py in create_object_detection_table(conn, data_path, coord_type, output, local_path, image_size)
   1287     conn.runcode(code = fmt_code, _messagelevel = 'error')
   1288     cls_col_format_length = conn.columninfo(output).ColumnInfo.loc[0][3]
-> 1289     cls_col_format_length = cls_col_format_length if cls_col_format_length >= len('NoObject') else len('NoObject')
   1290 
   1291     conn.altertable(name = output, columns = [dict(name = 'Var1', rename = var_name[0]),

TypeError: '>=' not supported between instances of 'str' and 'int'
```

I'm using the following environment:
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)

Python version 3.7.1

dlpy version 1.1.2
swat version 1.6.0

**Comment by wenyushi** [comment]
Hi, I think the error was fixed before. Please install the latest DLPy from git clone.

**Comment by Mespith** [comment]
I thought version 1.1.2 was already the latest version of dlpy... Nevertheless, version 1.1.3.dev0 was installed and the error still persists.

**Comment by Mentos05** [comment]
> I thought version 1.1.2 was already the latest version of dlpy... Nevertheless, version 1.1.3.dev0 was installed and the error still persists.

The error is gone after installing directly from github. Use: pip install git+https://github.com/sassoftware/python-dlpy.git@master

**Comment by Mespith** [comment]
Hi, I'm not totally convinced that this is the only solution. I used the exact same data and code on another environment where dlpy version 1.1.2 was running and I did not get the error.

**Comment by fede-citti** [comment]
@Mespith which Viya version are you using?

**Comment by Mespith** [comment]
The environment where it does not work is Viya 3.5 and it did work with Viya 3.4
